#GUI window options
title: "Spacejockey GUI"

#2x2 meter configuration for SVE Redux
width: 1070
height: 700
scale: 0.002  #20 cm / 100px
origin/x: 535
origin/y: 350

#how close to space view waypoints for range inspection
inspectionSize: .2 #20 cm