#GUI window options
title: "Spacejockey GUI"

#2x2 meter configuration for SVE Redux
width: 700
height: 700
scale: 0.00286  #28.6 cm / 100px
origin/x: 350
origin/y: 350

#how close to space view waypoints for range inspection
inspectionSize: .3 #30 cm