#Soft constraints for major planning actions
#distances are in meters

frame_names/front_foot: 'front_foot'
frame_names/center_foot: 'robot'
frame_names/rear_foot: 'rear_foot'

#body limits
extend/max: .34 #linear actuator reach
extend/min: .26
angle/max: deg(15)

#Tkinter window options
width: 600
height: 600
scale: 0.005  #50 cm / 100px
origin/x: 300
origin/y: 300