#This tells joint_state_publisher and the IK engine
#to use the URDF safety_controller limits, not the hardware limits
use_smallest_joint_limits: False

#these are the default settings for the joint_state_publisher node
source_list: ["joint_minor"]
use_gui: True

#these are used for lash compensation settings
#TODO: look if we can hack these into the URDF
joints/name: ['center_swivel', 'fore_base_pitch', 'aft_base_pitch', 'front_pitch', 'rear_pitch', 'fore_extend', 'aft_extend', 'front_attach', 'center_attach', 'rear_attach']
joints/ratios:     [3.0,              2.0,            2.0,             2.0,          2.0,         100,           100]
joints/lash/radii: [2.25,           1.5,              1.5,             1.5,          1.5,         100,           100]
joints/lash/lash: 0.01

#this is the joint-names -> adafruit PWM channel # mapping
# channels in order, 0 -> 15, could be redone as a dict()
arduino/joint_wiring: ['front_attach', 'front_pitch', 'fore_extend', 'fore_base_pitch', 'center_swivel', 'center_attach', '', '', 'aft_base_pitch', 'aft_extend', 'rear_pitch', 'rear_attach', '', '', '', 'pwm_feedback']
arduino/servo/min: 900
arduino/servo/max: 2100

#these are used by joint_state_publisher to set the default joint 'safe position'
zeros/center_swivel: 0.0
zeros/fore_base_pitch: -0.065
zeros/aft_base_pitch: -0.065
zeros/front_pitch: 0.065
zeros/rear_pitch: 0.065
zeros/fore_extend: 0.198
zeros/aft_extend: 0.198