#Soft constraints for major planning actions
#distances are in meters

#body limits
extend/max: .34 #linear actuator reach
extend/min: .26
angle/max: deg(15)

#camera reach
view/extend: .3 # where to put the foot when viewing
view/extendHeight: .1
view/max: .6 #camera view range
view/min: .35
view/opt: .5 # optimum camera viewing angle
view/radius: .2

#Tkinter window options
window/width: 600
window/height: 600
window/scale: 0.005  #50 cm / 100px
window/origin/x: 300
window/origin/y: 300

#Subplanner options
move/detachHeight: .01 #ground clearance at detachment
move/clearHeight: .06  #ground clearance at peak