#Soft constraints for major planning actions
#distances are in meters

frame_names/front_foot: 'front_foot'
frame_names/center_foot: 'robot'
frame_names/rear_foot: 'rear_foot'

#body limits
extend/max: .34 #linear actuator reach
extend/min: .26
angle/max: deg(15)
angle/dead: deg(1) #angular 'dead_zone' for planner error

#camera reach
view/extend: .3 # where to put the foot when viewing
view/extendHeight: .12
view/max: .7 #camera view range
view/min: .5
view/opt: .6 # optimum camera viewing angle
view/radius: .2

#Subplanner options
move/detachHeight: .05 #ground clearance at detachment
move/clearHeight: .05  #ground clearance at peak