#Soft constraints for major planning actions
#distances are in meters

#static starting frames...
static_tfs/robot: [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 1.0]]
static_tfs/marker_0: [[-1.5, 0.5, 0.0], [0.0, 0.0, 0.0, 1.0]]
static_tfs/marker_1: [[0.0, 0.5, 0.0], [0.0, 0.0, 0.0, 1.0]]
static_tfs/marker_2: [[1.5, 0.5, 0.0], [0.0, 0.0, 0.0, 1.0]]
static_tfs/marker_3: [[1.5, -0.5, 0.0], [0.0, 0.0, 0.0, 1.0]]
static_tfs/marker_4: [[0.0, -0.5, 0.0], [0.0, 0.0, 0.0, 1.0]]
static_tfs/marker_5: [[-1.5, -0.5, 0.0], [0.0, 0.0, 0.0, 1.0]]
